config/routes.rb
Rails.application.routes.draw do
  resources :analysis_results
  resources :sentences
  resources :reviews
  resources :business_owners

  get 'welcome' => 'business_owners#home'

  get 'login' => 'business_owners#login'

  get 'index' => 'business_owners#index'

  get 'about' => 'business_owners#about'

 

  root :to => 'business_owners#home'

#   get "business_owners/hello" => "your-controller#your/action"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sentence.rb
class Sentence < ApplicationRecord
    belongs_to :review
    has_many :business_owners, through: :review

    scope :rankpos, -> { order(sentiment_score: :desc) }
    scope :rankneg, -> { order(sentiment_score: :asc) }
    scope :positive, -> { where(sentiment_label: 'positive') }
    scope :negative, -> { where(sentiment_label: 'negative') }
    scope :rankdate, -> { joins(:review).order('date DESC') }


    def self.overallScore 
    	score = 0
    	count = 0
    	reviews = Sentence.all
    	reviews.each do |sentiment|
    		score = score + sentiment.sentiment_score
    		count = count + 1
    	end
    	percentage = score/count
    	if score >= 0
    		percentage = ((percentage + 1)/2)*100 
    		percentage = (percentage *100).round/100
    		result = percentage.to_s + '%'
    		return result
    	else
    		percentage = ((percentage.abs + 1)/2)*100
    		percentage =(percentage *100).round/100 
    		result = percentage.to_s + '%'
    		return result
    	end
    end

    



    def self.numSentences 
        count = 0
        reviews = Sentence.all
        reviews.each do |sentiment|
            count = count + 1
        end
        return count
    end

    def self.numPositive 
        count = 0
        reviews = Sentence.positive.all
        reviews.each do |sentiment|
            count = count + 1
        end
        return count
    end

    def self.numNegative 
        count = 0
        reviews = Sentence.negative.all
        reviews.each do |sentiment|
            count = count + 1
        end
        return count
    end

end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :set_sentence, only: [:show, :edit, :update, :destroy]

  # GET /sentences
  # GET /sentences.json
  def index
    @sentences = Sentence.all
    # @sentence = Sentence.new
    # @sentence = Sentence.run_api_analysis
  end

  # GET /sentences/1
  # GET /sentences/1.json
  def show
  end

  # GET /sentences/new
  def new
    @sentence = Sentence.new
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences
  # POST /sentences.json
  def create
    @sentence = Sentence.new(sentence_params)

    respond_to do |format|
      if @sentence.save
        format.html { redirect_to @sentence, notice: 'Sentence was successfully created.' }
        format.json { render :show, status: :created, location: @sentence }
      else
        format.html { render :new }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sentences/1
  # PATCH/PUT /sentences/1.json
  def update
    respond_to do |format|
      if @sentence.update(sentence_params)
        format.html { redirect_to @sentence, notice: 'Sentence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sentence }
      else
        format.html { render :edit }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentences/1
  # DELETE /sentences/1.json
  def destroy
    @sentence.destroy
    respond_to do |format|
      format.html { redirect_to sentences_url, notice: 'Sentence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sentence
      @sentence = Sentence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sentence_params
      params.require(:sentence).permit(:review_id, :sentence_content)
    end
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/sentences/_form.html.erb
<%= form_with(model: sentence, local: true) do |form| %>
  <% if sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
      <% sentence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :review_id %>
    <%= form.text_field :review_id, id: :sentence_review_id %>
  </div>

  <div class="field">
    <%= form.label :sentence_content %>
    <%= form.text_field :sentence_content, id: :sentence_sentence_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sentences/edit.html.erb
<h1>Editing Sentence</h1>

<%= render 'form', sentence: @sentence %>

<%= link_to 'Show', @sentence %> |
<%= link_to 'Back', sentences_path %>

app/views/sentences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sentences</h1>

<table>
  <thead>
    <tr>
      <th>Review</th>
      <th>Sentence content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sentences.each do |sentence| %>
      <tr>
        <td><%= sentence.review_id %></td>
        <td><%= sentence.sentence_content %></td>
        <td><%= link_to 'Show', sentence %></td>
        <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
        <td><%= link_to 'Destroy', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sentence', new_sentence_path %>

app/views/sentences/new.html.erb
<h1>New Sentence</h1>

<%= render 'form', sentence: @sentence %>

<%= link_to 'Back', sentences_path %>

app/views/sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Review:</strong>
  <%= @sentence.review_id %>
</p>

<p>
  <strong>Sentence content:</strong>
  <%= @sentence.sentence_content %>
</p>

<%= link_to 'Edit', edit_sentence_path(@sentence) %> |
<%= link_to 'Back', sentences_path %>