config/routes.rb
Rails.application.routes.draw do
  resources :analysis_results
  resources :sentences
  resources :reviews
  resources :business_owners

  get 'welcome' => 'business_owners#home'

  get 'login' => 'business_owners#login'

  get 'index' => 'business_owners#index'

  get 'about' => 'business_owners#about'

 

  root :to => 'business_owners#home'

#   get "business_owners/hello" => "your-controller#your/action"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analysis_result.rb
class AnalysisResult < ApplicationRecord
 belongs_to :sentence

    # require 'rest-client'
    # require 'json'

    def run_api_analysis(sentence_id)
        # # uri = URI.parse("https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2017-02-27&text=I%20still%20have%20a%20dream%2C%20a%20dream%20deeply%20rooted%20in%20the%20American%20dream%20%E2%80%93%20one%20day%20this%20nation%20will%20rise%20up%20and%20live%20up%20to%20its%20creed%2C%20%22We%20hold%20these%20truths%20to%20be%20self%20evident%3A%20that%20all%20men%20are%20created%20equal.&features=sentiment,keywords")
        # # request = Net::HTTP::Get.new(uri)
        # # request.basic_auth("5d047b97-caec-4304-a13b-ae28a9740c56", "WYmQLD06Ibra")

        # response = RestClient::Request.execute method: :get, url: "https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2017-02-27&text=I%20still%20have%20a%20dream%2C%20a%20dream%20deeply%20rooted%20in%20the%20American%20dream%20%E2%80%93%20one%20day%20this%20nation%20will%20rise%20up%20and%20live%20up%20to%20its%20creed%2C%20%22We%20hold%20these%20truths%20to%20be%20self%20evident%3A%20that%20all%20men%20are%20created%20equal.&features=sentiment,keywords", user: '5d047b97-caec-4304-a13b-ae28a9740c56', password: 'WYmQLD06Ibra'

        # # render :json => response.body
        # json_response = JSON.parse(response.body)
        # self.sentence_id = sentence_id
        # sentiment_label = json_response["sentiment"]["document"]["label"]
        # sentiment_score = json_response["sentiment"]["document"]["score"]
        # puts sentiment_label
        # puts sentiment_score
        # self.sentiment_score = sentiment_score
        # self.sentiment_label = sentiment_label

        # # return (sentence_id, sentiment_label, sentiment_score)

    end
    
end

app/controllers/analysis_results_controller.rb
class AnalysisResultsController < ApplicationController
  before_action :set_analysis_result, only: [:show, :edit, :update, :destroy]

  # GET /analysis_results
  # GET /analysis_results.json
  def index
    @analysis_results = AnalysisResult.all
    @positive = AnalysisResult.positive.all
    @negative = AnalysisResult.negative.all
  end

  # GET /analysis_results/1
  # GET /analysis_results/1.json
  def show
    @positive = AnalysisResult.positive.all
    @negative = AnalysisResult.negative.all
  end

  # GET /analysis_results/new
  def new
    @analysis_result = AnalysisResult.new
  end

  # GET /analysis_results/1/edit
  def edit
  end

  # POST /analysis_results
  # POST /analysis_results.json
  def create
    @analysis_result = AnalysisResult.new(analysis_result_params)

    respond_to do |format|
      if @analysis_result.save
        format.html { redirect_to @analysis_result, notice: 'Analysis result was successfully created.' }
        format.json { render :show, status: :created, location: @analysis_result }
      else
        format.html { render :new }
        format.json { render json: @analysis_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analysis_results/1
  # PATCH/PUT /analysis_results/1.json
  def update
    respond_to do |format|
      if @analysis_result.update(analysis_result_params)
        format.html { redirect_to @analysis_result, notice: 'Analysis result was successfully updated.' }
        format.json { render :show, status: :ok, location: @analysis_result }
      else
        format.html { render :edit }
        format.json { render json: @analysis_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analysis_results/1
  # DELETE /analysis_results/1.json
  def destroy
    @analysis_result.destroy
    respond_to do |format|
      format.html { redirect_to analysis_results_url, notice: 'Analysis result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis_result
      @analysis_result = AnalysisResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analysis_result_params
      params.require(:analysis_result).permit(:sentence_id, :sentiment_label, :sentiment_score)
    end
end

app/helpers/analysis_results_helper.rb
module AnalysisResultsHelper
end

app/views/analysis_results/_form.html.erb
<%= form_with(model: analysis_result, local: true) do |form| %>
  <% if analysis_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analysis_result.errors.count, "error") %> prohibited this analysis_result from being saved:</h2>

      <ul>
      <% analysis_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sentence_id %>
    <%= form.number_field :sentence_id, id: :analysis_result_sentence_id %>
  </div>

  <div class="field">
    <%= form.label :sentiment_label %>
    <%= form.text_field :sentiment_label, id: :analysis_result_sentiment_label %>
  </div>

  <div class="field">
    <%= form.label :sentiment_score %>
    <%= form.text_field :sentiment_score, id: :analysis_result_sentiment_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/analysis_results/edit.html.erb
<h1>Editing Analysis Result</h1>

<%= render 'form', analysis_result: @analysis_result %>

<%= link_to 'Show', @analysis_result %> |
<%= link_to 'Back', analysis_results_path %>

app/views/analysis_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analysis Results</h1>

<table>
  <thead>
    <tr>
      <th>Sentence</th>
      <th>Sentiment label</th>
      <th>Sentiment score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analysis_results.each do |analysis_result| %>
      <tr>
        <td><%= analysis_result.sentence_id %></td>
        <td><%= analysis_result.sentiment_label %></td>
        <td><%= analysis_result.sentiment_score %></td>
        <td><%= link_to 'Show', analysis_result %></td>
        <td><%= link_to 'Edit', edit_analysis_result_path(analysis_result) %></td>
        <td><%= link_to 'Destroy', analysis_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analysis Result', new_analysis_result_path %>

app/views/analysis_results/new.html.erb
<h1>New Analysis Result</h1>

<%= render 'form', analysis_result: @analysis_result %>

<%= link_to 'Back', analysis_results_path %>

app/views/analysis_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sentence:</strong>
  <%= @analysis_result.sentence_id %>
</p>

<p>
  <strong>Sentiment label:</strong>
  <%= @analysis_result.sentiment_label %>
</p>

<p>
  <strong>Sentiment score:</strong>
  <%= @analysis_result.sentiment_score %>
</p>

<%= link_to 'Edit', edit_analysis_result_path(@analysis_result) %> |
<%= link_to 'Back', analysis_results_path %>