config/routes.rb
Rails.application.routes.draw do
  resources :analysis_results
  resources :sentences
  resources :reviews
  resources :business_owners

  get 'welcome' => 'business_owners#home'

  get 'login' => 'business_owners#login'

  get 'index' => 'business_owners#index'

  get 'about' => 'business_owners#about'

 

  root :to => 'business_owners#home'

#   get "business_owners/hello" => "your-controller#your/action"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/business_owner.rb
class BusinessOwner < ApplicationRecord
    has_many :reviews
    has_many :sentences, through: :reviews
end

app/controllers/business_owners_controller.rb
class BusinessOwnersController < ApplicationController
  before_action :set_business_owner, only: [:show, :edit, :update, :destroy]

  # GET /business_owners
  # GET /business_owners.json

  def home
  end

  def login
  end
  
  def index
    @business_owners = BusinessOwner.all
    @sentence = Sentence.all
    @reviews = Review.all 
    @positive = Sentence.positive.rankdate.all
    @negative = Sentence.negative.rankdate.all

    @review = Review.all
    
  end

  # GET /business_owners/1
  # GET /business_owners/1.json
  def show
  end

  # GET /business_owners/new
  def new
    @business_owner = BusinessOwner.new
  end

  # GET /business_owners/1/edit
  def edit
  end

  # POST /business_owners
  # POST /business_owners.json
  def create
    @business_owner = BusinessOwner.new(business_owner_params)

    respond_to do |format|
      if @business_owner.save
        format.html { redirect_to @business_owner, notice: 'Business owner was successfully created.' }
        format.json { render :show, status: :created, location: @business_owner }
      else
        format.html { render :new }
        format.json { render json: @business_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_owners/1
  # PATCH/PUT /business_owners/1.json
  def update
    respond_to do |format|
      if @business_owner.update(business_owner_params)
        format.html { redirect_to @business_owner, notice: 'Business owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_owner }
      else
        format.html { render :edit }
        format.json { render json: @business_owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_owners/1
  # DELETE /business_owners/1.json
  def destroy
    @business_owner.destroy
    respond_to do |format|
      format.html { redirect_to @business_owner, notice: 'Business owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_owner
      @business_owner = BusinessOwner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_owner_params
      params.require(:business_owner).permit(:user_name, :password, :business_name, :email)
    end
end

app/helpers/business_owners_helper.rb
module BusinessOwnersHelper
end

app/views/business_owners/_form.html.erb
<%= form_with(model: business_owner, local: true) do |form| %>
  <% if business_owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_owner.errors.count, "error") %> prohibited this business_owner from being saved:</h2>

      <ul>
      <% business_owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, id: :business_owner_user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :business_owner_password %>
  </div>

  <div class="field">
    <%= form.label :business_name %>
    <%= form.text_field :business_name, id: :business_owner_business_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :business_owner_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/business_owners/about.html.erb
<div class="bs-docs-section">
  <h1 id="history" class="page-header" style="font-size: 60px;">360 Review</h1>

  <p class="lead">An application that utilizes sentiment analysis to provide businesses owners with clear common sentiments (both positive and negative) that surround their business.</p>
  <p>Businesses operate to serve their customers, so there is value in catering to a customer’s specific needs as presented in the unadulterated form of online reviews. The stakeholders and users are the businesses analyzing their reviews and also, indirectly, the customers that businesses will serve. </p>
</div>



<div class="bs-docs-section">
  <h1 id="team" class="page-header">Value</h1>

  <p class="lead">The value of this application lies in providing businesses with specific measures of sentiment from their customers, and allowing business owners to evaluate their strengths and weaknesses to understand potential growth areas. </p>
  <br>

  <h2 id="team-core" class="page-header">Sentiment Analysis</h2>
<p>Sentiment analysis is able to check any block of text, and evaluate whether it is positive or negative, or even smaller sentiments such as confident, tentative, sad, excited etc.. For businesses, sentiment analysis extracts feelings and meaning from huge amounts of text, allowing business owners to measure existing public perception of their business. <p>

app/views/business_owners/edit.html.erb
<h1>Editing Business Owner</h1>

<%= render 'form', business_owner: @business_owner %>

<%= link_to 'Show', @business_owner %> |
<%= link_to 'Back', business_owners_path %>

app/views/business_owners/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Landing Page</title>

    <!-- Bootstrap core CSS -->
    <link href="../../assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/stylesheets/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="/Users/avnipherwani/360-review/app/assets/stylesheets/cover.css" rel="stylesheet"> -->

    <link href="carousel.css" rel="stylesheet">

    <script src="../../assets/js/ie-emulation-modes-warning.js">    </script>

  </head>
  
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="welcome">360-Review</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="login">Login</a></li>
          </ul>
        </div>
      </div>
    </nav>


           <%= image_tag("pic3.png", :alt => "home image", :class => "first-slide") %>
          <div class="container">
            <div class="home">
               <h1>360-REVIEW</h1>
              <h2>CUSTOMER REVIEWS. ANALYZE. VALUE</h2>
          <h3>Instant access to real time restaurant sentiment analysis</h3>
          <br>
          <p><a class="btn btn-lg btn-primary" href="login" role="button">Login</a></p>
        </div>
            </div>
          
        

            
  <div class="text">
  <p>An application that utilizes sentiment analysis to provide businesses owners with clear common sentiments (both positive and negative) that surround their business.
  Businesses operate to serve their customers, so there is value in catering to a customer’s specific needs as presented in the unadulterated form of online reviews. The stakeholders and users are the businesses analyzing their reviews and also, indirectly, the customers that businesses will serve. </p>
</div>
<hr>



    <!-- Three columns of text below the carousel -->
    <div class="features">
      <div class="row">
        <div class="col-lg-4">
          <%= image_tag("review.png", :alt => "home image", :class => "img-rounded") %>
          <h2>Diverse Sources</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag("analytics.png", :alt => "home image", :class => "img-rounded") %>
          <h2>In-Depth Analytics</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag("insight.png", :alt => "home image", :class => "rounded") %>
          <h2>Unique Insights</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
    </div>

    
     

    

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
   <footer>
  &copy; Copyright 360-Review
</footer>
</html>

app/views/business_owners/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Login Template</title>

    <!-- Bootstrap core CSS -->
    <link href="login.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="welcome">360-Review</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="welcome">Home</a></li>
            <li><a href="login">Login</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div id="login">
    <div class="container">
    <div class="top">
      <h1 id="title" class="hidden"><span id="logo">Daily <span>UI</span></span></h1>
    </div>
    <div class="login-box animated fadeInUp">
      <div class="box-header">
        <h2>Log In</h2>
      </div>
      <label for="username">Username</label>
      <br/>
      <input type="text" id="username">
      <br/>
      <label for="password">Password</label>
      <br/>
      <input type="password" id="password">
      <br/>
      <button><a href="business_owners">Sign In</a></button>
      <br/>
      <a href="#"><p class="small">Forgot your password?</p></a>
    </div>
  </div>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </div>
  </body>

<footer>
  &copy; Copyright 360-Review
</footer>
</html>

app/views/business_owners/new.html.erb
<h1>New Business Owner</h1>

<%= render 'form', business_owner: @business_owner %>

<%= link_to 'Back', business_owners_path %>

app/views/business_owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @business_owner.user_name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @business_owner.password %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @business_owner.business_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business_owner.email %>
</p>

<%= link_to 'Edit', edit_business_owner_path(@business_owner) %> |
<%= link_to 'Back', business_owners_path %>